apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdns
  namespace: default
  labels:
    app: pdns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pdns
  namespace: default
  labels:
    app: pdns
rules:
  - apiGroups:
      - ""
      - tanelmae.github.com
    resources:
      - pods
      - privatedns
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pdns
  namespace: default
  labels:
    app: pdns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pdns
subjects:
  - kind: ServiceAccount
    name: pdns
    namespace: default
